### ISSUE TITLE
core dump when many nodes connected

### ISSUE THREAD

**Issue by spassmo** [pttlink/Asterisk#50]
Having problems with core dumps when multiple large hubs connect together.  

Same issue as https://community.allstarlink.org/t/asterisk-core-dumps/16050

https://github.com/AllStarLink/Asterisk/blob/2a50097040b89c05312ec0c025d9073003f140df/asterisk/apps/app_rpt.c#L23122

This appears to be relevant output from `echo bt | sudo gdb /usr/sbin/asterisk /core`

`Core was generated by `/usr/sbin/asterisk -g -f -C /etc/asterisk/asterisk.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f27b5eb8db6 in rpt_exec (chan=0x7f2788012630, data=<optimized out>) at app_rpt.c:23122

23122                   if ((!strncasecmp(l->chan->name,"echolink",8)) ||
[Current thread is 1 (Thread 0x7f277a8b6700 (LWP 5539))]
(gdb) #0  0x00007f27b5eb8db6 in rpt_exec (chan=0x7f2788012630, data=<optimized out>) at app_rpt.c:23122
#1  0x0000000000489173 in pbx_exec (data=0x7f277a8b1cd0, app=0xd70930, c=0x7f2788012630) at pbx.c:537
#2  pbx_extension_helper (c=c@entry=0x7f2788012630, context=context@entry=0x7f2788012880 "radio-secure", exten=exten@entry=0x7f27880128d0 "2560", priority=1, label=label@entry=0x0,
    callerid=<optimized out>, action=action@entry=E_SPAWN, con=0x0) at pbx.c:1862
#3  0x00000000004908fc in ast_spawn_extension (callerid=<optimized out>, priority=<optimized out>, exten=0x7f27880128d0 "2560", context=0x7f2788012880 "radio-secure", c=0x7f2788012630) at pbx.c:2317
#4  __ast_pbx_run (c=c@entry=0x7f2788012630) at pbx.c:2406
#5  0x0000000000491499 in pbx_thread (data=data@entry=0x7f2788012630) at pbx.c:2621
#6  0x00000000004c0169 in dummy_start (data=<optimized out>) at utils.c:925
#7  0x00007f27c51f14a4 in start_thread (arg=0x7f277a8b6700) at pthread_create.c:456
#8  0x00007f27c47eed0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) quit
`

**Comment by KG7QIN** [comment]
By chance can you provide one or more core dumps for this?  It would make seeing what is happening better.

**Comment by KG7QIN** [comment]
No additional information has been provided.  Closing this issue.

**Comment by spassmo** [comment]
It's still happening on a daily basis.   I'll work on getting more core dumps.  Is there anything specific needed?

**Comment by KG7QIN** [comment]
Yes, change your system to allow coredumps and then please attach them to this issue.
It will allow review of the issue at hand and help track down the code causing it.

You can also login to the ticketing system at https://rt.allstarlink.org and submit a ticket and upload the coredump.

Thanks.

**Comment by KG7QIN** [comment]
No additional requested information has been provided.  Closing issue.

**Comment by KG7QIN** [comment]
Note this issue is being locked.  @spassmo if you still wish to receive assistance with this then please open a new issue request and use the new issue template.  Thank you.
